// Code generated by ogen, DO NOT EDIT.

package api

import (
	"fmt"
	"net/http"

	"github.com/go-faster/errors"
	"github.com/go-faster/jx"
	ht "github.com/ogen-go/ogen/http"
	"github.com/ogen-go/ogen/validate"
)

func encodeConfigGetResponse(response ConfigGetRes, w http.ResponseWriter) error {
	switch response := response.(type) {
	case *Config:
		if err := func() error {
			if err := response.Validate(); err != nil {
				return err
			}
			return nil
		}(); err != nil {
			return errors.Wrap(err, "validate")
		}
		w.Header().Set("Content-Type", "application/json; charset=utf-8")
		w.WriteHeader(200)

		e := new(jx.Encoder)
		response.Encode(e)
		if _, err := e.WriteTo(w); err != nil {
			return errors.Wrap(err, "write")
		}

		return nil

	case *ConfigGetForbidden:
		w.WriteHeader(403)

		return nil

	default:
		return errors.Errorf("unexpected response type: %T", response)
	}
}

func encodeConfigPostResponse(response ConfigPostRes, w http.ResponseWriter) error {
	switch response := response.(type) {
	case *Config:
		if err := func() error {
			if err := response.Validate(); err != nil {
				return err
			}
			return nil
		}(); err != nil {
			return errors.Wrap(err, "validate")
		}
		w.Header().Set("Content-Type", "application/json; charset=utf-8")
		w.WriteHeader(200)

		e := new(jx.Encoder)
		response.Encode(e)
		if _, err := e.WriteTo(w); err != nil {
			return errors.Wrap(err, "write")
		}

		return nil

	case *ConfigPostForbidden:
		w.WriteHeader(403)

		return nil

	default:
		return errors.Errorf("unexpected response type: %T", response)
	}
}

func encodeCreateReviewResponse(response CreateReviewRes, w http.ResponseWriter) error {
	switch response := response.(type) {
	case *Review:
		if err := func() error {
			if err := response.Validate(); err != nil {
				return err
			}
			return nil
		}(); err != nil {
			return errors.Wrap(err, "validate")
		}
		w.Header().Set("Content-Type", "application/json; charset=utf-8")
		w.WriteHeader(201)

		e := new(jx.Encoder)
		response.Encode(e)
		if _, err := e.WriteTo(w); err != nil {
			return errors.Wrap(err, "write")
		}

		return nil

	case *CreateReviewBadRequest:
		w.WriteHeader(400)

		return nil

	case *CreateReviewNotFound:
		w.WriteHeader(404)

		return nil

	case *CreateReviewConflict:
		w.WriteHeader(409)

		return nil

	default:
		return errors.Errorf("unexpected response type: %T", response)
	}
}

func encodeCreateTicketResponse(response CreateTicketRes, w http.ResponseWriter) error {
	switch response := response.(type) {
	case *Ticket:
		if err := func() error {
			if err := response.Validate(); err != nil {
				return err
			}
			return nil
		}(); err != nil {
			return errors.Wrap(err, "validate")
		}
		w.Header().Set("Content-Type", "application/json; charset=utf-8")
		w.WriteHeader(201)

		e := new(jx.Encoder)
		response.Encode(e)
		if _, err := e.WriteTo(w); err != nil {
			return errors.Wrap(err, "write")
		}

		return nil

	case *CreateTicketBadRequest:
		w.WriteHeader(400)

		return nil

	case *CreateTicketUnauthorized:
		w.WriteHeader(401)

		return nil

	case *CreateTicketForbidden:
		w.WriteHeader(403)

		return nil

	default:
		return errors.Errorf("unexpected response type: %T", response)
	}
}

func encodeDeleteReviewResponse(response *DeleteReviewNoContent, w http.ResponseWriter) error {
	w.WriteHeader(204)

	return nil
}

func encodeDeleteTicketByIDResponse(response DeleteTicketByIDRes, w http.ResponseWriter) error {
	switch response := response.(type) {
	case *DeleteTicketByIDNoContent:
		w.WriteHeader(204)

		return nil

	case *DeleteTicketByIDUnauthorized:
		w.WriteHeader(401)

		return nil

	case *DeleteTicketByIDForbidden:
		w.WriteHeader(403)

		return nil

	case *DeleteTicketByIDNotFound:
		w.WriteHeader(404)

		return nil

	default:
		return errors.Errorf("unexpected response type: %T", response)
	}
}

func encodeGetTicketByIDResponse(response GetTicketByIDRes, w http.ResponseWriter) error {
	switch response := response.(type) {
	case *GetTicketByIDOK:
		if err := func() error {
			if err := response.Validate(); err != nil {
				return err
			}
			return nil
		}(); err != nil {
			return errors.Wrap(err, "validate")
		}
		w.Header().Set("Content-Type", "application/json; charset=utf-8")
		w.WriteHeader(200)

		e := new(jx.Encoder)
		response.Encode(e)
		if _, err := e.WriteTo(w); err != nil {
			return errors.Wrap(err, "write")
		}

		return nil

	case *GetTicketByIDUnauthorized:
		w.WriteHeader(401)

		return nil

	case *GetTicketByIDNotFound:
		w.WriteHeader(404)

		return nil

	default:
		return errors.Errorf("unexpected response type: %T", response)
	}
}

func encodeGetTicketsResponse(response GetTicketsRes, w http.ResponseWriter) error {
	switch response := response.(type) {
	case *GetTicketsOKApplicationJSON:
		if err := func() error {
			if err := response.Validate(); err != nil {
				return err
			}
			return nil
		}(); err != nil {
			return errors.Wrap(err, "validate")
		}
		w.Header().Set("Content-Type", "application/json; charset=utf-8")
		w.WriteHeader(200)

		e := new(jx.Encoder)
		response.Encode(e)
		if _, err := e.WriteTo(w); err != nil {
			return errors.Wrap(err, "write")
		}

		return nil

	case *GetTicketsBadRequest:
		w.WriteHeader(400)

		return nil

	case *GetTicketsUnauthorized:
		w.WriteHeader(401)

		return nil

	default:
		return errors.Errorf("unexpected response type: %T", response)
	}
}

func encodeTicketsTicketIdNotesNoteIdDeleteResponse(response *TicketsTicketIdNotesNoteIdDeleteNoContent, w http.ResponseWriter) error {
	w.WriteHeader(204)

	return nil
}

func encodeTicketsTicketIdNotesNoteIdPutResponse(response TicketsTicketIdNotesNoteIdPutRes, w http.ResponseWriter) error {
	switch response := response.(type) {
	case *TicketsTicketIdNotesNoteIdPutOK:
		w.WriteHeader(200)

		return nil

	case *TicketsTicketIdNotesNoteIdPutForbidden:
		w.WriteHeader(403)

		return nil

	default:
		return errors.Errorf("unexpected response type: %T", response)
	}
}

func encodeTicketsTicketIdNotesPostResponse(response *Note, w http.ResponseWriter) error {
	if err := func() error {
		if err := response.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		return errors.Wrap(err, "validate")
	}
	w.Header().Set("Content-Type", "application/json; charset=utf-8")
	w.WriteHeader(201)

	e := new(jx.Encoder)
	response.Encode(e)
	if _, err := e.WriteTo(w); err != nil {
		return errors.Wrap(err, "write")
	}

	return nil
}

func encodeUpdateReviewResponse(response UpdateReviewRes, w http.ResponseWriter) error {
	switch response := response.(type) {
	case *UpdateReviewOK:
		w.WriteHeader(200)

		return nil

	case *UpdateReviewForbidden:
		w.WriteHeader(403)

		return nil

	case *UpdateReviewNotFound:
		w.WriteHeader(404)

		return nil

	default:
		return errors.Errorf("unexpected response type: %T", response)
	}
}

func encodeUpdateTicketByIDResponse(response UpdateTicketByIDRes, w http.ResponseWriter) error {
	switch response := response.(type) {
	case *UpdateTicketByIDOK:
		w.WriteHeader(200)

		return nil

	case *UpdateTicketByIDBadRequest:
		w.WriteHeader(400)

		return nil

	case *UpdateTicketByIDUnauthorized:
		w.WriteHeader(401)

		return nil

	case *UpdateTicketByIDForbidden:
		w.WriteHeader(403)

		return nil

	case *UpdateTicketByIDNotFound:
		w.WriteHeader(404)

		return nil

	default:
		return errors.Errorf("unexpected response type: %T", response)
	}
}

func encodeUsersGetResponse(response []User, w http.ResponseWriter) error {
	if err := func() error {
		if response == nil {
			return errors.New("nil is invalid value")
		}
		var failures []validate.FieldError
		for i, elem := range response {
			if err := func() error {
				if err := elem.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				failures = append(failures, validate.FieldError{
					Name:  fmt.Sprintf("[%d]", i),
					Error: err,
				})
			}
		}
		if len(failures) > 0 {
			return &validate.Error{Fields: failures}
		}
		return nil
	}(); err != nil {
		return errors.Wrap(err, "validate")
	}
	w.Header().Set("Content-Type", "application/json; charset=utf-8")
	w.WriteHeader(200)

	e := new(jx.Encoder)
	e.ArrStart()
	for _, elem := range response {
		elem.Encode(e)
	}
	e.ArrEnd()
	if _, err := e.WriteTo(w); err != nil {
		return errors.Wrap(err, "write")
	}

	return nil
}

func encodeUsersPutResponse(response UsersPutRes, w http.ResponseWriter) error {
	switch response := response.(type) {
	case *UsersPutOK:
		w.WriteHeader(200)

		return nil

	case *UsersPutForbidden:
		w.WriteHeader(403)

		return nil

	default:
		return errors.Errorf("unexpected response type: %T", response)
	}
}

func encodeErrorResponse(response *ErrorResponseStatusCode, w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json; charset=utf-8")
	code := response.StatusCode
	if code == 0 {
		// Set default status code.
		code = http.StatusOK
	}
	w.WriteHeader(code)

	e := new(jx.Encoder)
	response.Response.Encode(e)
	if _, err := e.WriteTo(w); err != nil {
		return errors.Wrap(err, "write")
	}

	if code >= http.StatusInternalServerError {
		return errors.Wrapf(ht.ErrInternalServerErrorResponse, "code: %d, message: %s", code, http.StatusText(code))
	}
	return nil

}
