// Code generated by ogen, DO NOT EDIT.

package api

import (
	"fmt"
	"io"
	"mime"
	"net/http"

	"github.com/go-faster/errors"
	"github.com/go-faster/jx"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/validate"
)

func decodeConfigGetResponse(resp *http.Response) (res *ConfigGetOK, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response ConfigGetOK
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			return &response, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeConfigPostResponse(resp *http.Response) (res ConfigPostRes, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		return &ConfigPostOK{}, nil
	case 403:
		// Code 403.
		return &ConfigPostForbidden{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeTicketsGetResponse(resp *http.Response) (res TicketsGetRes, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response TicketsGetOKApplicationJSON
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			// Validate response.
			if err := func() error {
				if err := response.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return res, errors.Wrap(err, "validate")
			}
			return &response, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	case 401:
		// Code 401.
		return &TicketsGetUnauthorized{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeTicketsPostResponse(resp *http.Response) (res TicketsPostRes, _ error) {
	switch resp.StatusCode {
	case 201:
		// Code 201.
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response Ticket
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			// Validate response.
			if err := func() error {
				if err := response.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return res, errors.Wrap(err, "validate")
			}
			return &response, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	case 401:
		// Code 401.
		return &TicketsPostUnauthorized{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeTicketsTicketIdDeleteResponse(resp *http.Response) (res TicketsTicketIdDeleteRes, _ error) {
	switch resp.StatusCode {
	case 204:
		// Code 204.
		return &TicketsTicketIdDeleteNoContent{}, nil
	case 403:
		// Code 403.
		return &TicketsTicketIdDeleteForbidden{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeTicketsTicketIdGetResponse(resp *http.Response) (res TicketsTicketIdGetRes, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response TicketsTicketIdGetOK
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			// Validate response.
			if err := func() error {
				if err := response.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return res, errors.Wrap(err, "validate")
			}
			return &response, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	case 404:
		// Code 404.
		return &TicketsTicketIdGetNotFound{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeTicketsTicketIdNotesNoteIdDeleteResponse(resp *http.Response) (res *TicketsTicketIdNotesNoteIdDeleteNoContent, _ error) {
	switch resp.StatusCode {
	case 204:
		// Code 204.
		return &TicketsTicketIdNotesNoteIdDeleteNoContent{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeTicketsTicketIdNotesNoteIdPutResponse(resp *http.Response) (res TicketsTicketIdNotesNoteIdPutRes, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		return &TicketsTicketIdNotesNoteIdPutOK{}, nil
	case 403:
		// Code 403.
		return &TicketsTicketIdNotesNoteIdPutForbidden{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeTicketsTicketIdNotesNoteIdReviewsPostResponse(resp *http.Response) (res *Review, _ error) {
	switch resp.StatusCode {
	case 201:
		// Code 201.
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response Review
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			// Validate response.
			if err := func() error {
				if err := response.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return res, errors.Wrap(err, "validate")
			}
			return &response, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeTicketsTicketIdNotesNoteIdReviewsReviewIdDeleteResponse(resp *http.Response) (res *TicketsTicketIdNotesNoteIdReviewsReviewIdDeleteNoContent, _ error) {
	switch resp.StatusCode {
	case 204:
		// Code 204.
		return &TicketsTicketIdNotesNoteIdReviewsReviewIdDeleteNoContent{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeTicketsTicketIdNotesNoteIdReviewsReviewIdPutResponse(resp *http.Response) (res *TicketsTicketIdNotesNoteIdReviewsReviewIdPutOK, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		return &TicketsTicketIdNotesNoteIdReviewsReviewIdPutOK{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeTicketsTicketIdNotesPostResponse(resp *http.Response) (res *Note, _ error) {
	switch resp.StatusCode {
	case 201:
		// Code 201.
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response Note
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			// Validate response.
			if err := func() error {
				if err := response.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return res, errors.Wrap(err, "validate")
			}
			return &response, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeTicketsTicketIdPatchResponse(resp *http.Response) (res TicketsTicketIdPatchRes, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		return &TicketsTicketIdPatchOK{}, nil
	case 403:
		// Code 403.
		return &TicketsTicketIdPatchForbidden{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeUsersGetResponse(resp *http.Response) (res []User, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response []User
			if err := func() error {
				response = make([]User, 0)
				if err := d.Arr(func(d *jx.Decoder) error {
					var elem User
					if err := elem.Decode(d); err != nil {
						return err
					}
					response = append(response, elem)
					return nil
				}); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			// Validate response.
			if err := func() error {
				if response == nil {
					return errors.New("nil is invalid value")
				}
				var failures []validate.FieldError
				for i, elem := range response {
					if err := func() error {
						if err := elem.Validate(); err != nil {
							return err
						}
						return nil
					}(); err != nil {
						failures = append(failures, validate.FieldError{
							Name:  fmt.Sprintf("[%d]", i),
							Error: err,
						})
					}
				}
				if len(failures) > 0 {
					return &validate.Error{Fields: failures}
				}
				return nil
			}(); err != nil {
				return res, errors.Wrap(err, "validate")
			}
			return response, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeUsersPutResponse(resp *http.Response) (res UsersPutRes, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		return &UsersPutOK{}, nil
	case 403:
		// Code 403.
		return &UsersPutForbidden{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}
