// Code generated by ogen, DO NOT EDIT.

package api

import (
	"time"

	"github.com/go-faster/errors"
)

// 設定JSON (構造は未定).
type ConfigGetOK struct{}

// ConfigPostForbidden is response for ConfigPost operation.
type ConfigPostForbidden struct{}

func (*ConfigPostForbidden) configPostRes() {}

// ConfigPostOK is response for ConfigPost operation.
type ConfigPostOK struct{}

func (*ConfigPostOK) configPostRes() {}

type ConfigPostReq struct{}

type CreateReviewReq struct {
	Type ReviewType `json:"type"`
	// 承認の強さ.
	Weight  OptInt    `json:"weight"`
	Comment OptString `json:"comment"`
}

// GetType returns the value of Type.
func (s *CreateReviewReq) GetType() ReviewType {
	return s.Type
}

// GetWeight returns the value of Weight.
func (s *CreateReviewReq) GetWeight() OptInt {
	return s.Weight
}

// GetComment returns the value of Comment.
func (s *CreateReviewReq) GetComment() OptString {
	return s.Comment
}

// SetType sets the value of Type.
func (s *CreateReviewReq) SetType(val ReviewType) {
	s.Type = val
}

// SetWeight sets the value of Weight.
func (s *CreateReviewReq) SetWeight(val OptInt) {
	s.Weight = val
}

// SetComment sets the value of Comment.
func (s *CreateReviewReq) SetComment(val OptString) {
	s.Comment = val
}

// DeleteReviewNoContent is response for DeleteReview operation.
type DeleteReviewNoContent struct{}

// Ref: #/components/schemas/Note
type Note struct {
	// ノートID.
	ID       int64         `json:"id"`
	TicketID int64         `json:"ticket_id"`
	Type     NoteType      `json:"type"`
	Status   OptNoteStatus `json:"status"`
	// 作成者.
	Author string `json:"author"`
	// メッセージ本文.
	Content   string      `json:"content"`
	Reviews   []Review    `json:"reviews"`
	CreatedAt OptDateTime `json:"created_at"`
	UpdatedAt OptDateTime `json:"updated_at"`
}

// GetID returns the value of ID.
func (s *Note) GetID() int64 {
	return s.ID
}

// GetTicketID returns the value of TicketID.
func (s *Note) GetTicketID() int64 {
	return s.TicketID
}

// GetType returns the value of Type.
func (s *Note) GetType() NoteType {
	return s.Type
}

// GetStatus returns the value of Status.
func (s *Note) GetStatus() OptNoteStatus {
	return s.Status
}

// GetAuthor returns the value of Author.
func (s *Note) GetAuthor() string {
	return s.Author
}

// GetContent returns the value of Content.
func (s *Note) GetContent() string {
	return s.Content
}

// GetReviews returns the value of Reviews.
func (s *Note) GetReviews() []Review {
	return s.Reviews
}

// GetCreatedAt returns the value of CreatedAt.
func (s *Note) GetCreatedAt() OptDateTime {
	return s.CreatedAt
}

// GetUpdatedAt returns the value of UpdatedAt.
func (s *Note) GetUpdatedAt() OptDateTime {
	return s.UpdatedAt
}

// SetID sets the value of ID.
func (s *Note) SetID(val int64) {
	s.ID = val
}

// SetTicketID sets the value of TicketID.
func (s *Note) SetTicketID(val int64) {
	s.TicketID = val
}

// SetType sets the value of Type.
func (s *Note) SetType(val NoteType) {
	s.Type = val
}

// SetStatus sets the value of Status.
func (s *Note) SetStatus(val OptNoteStatus) {
	s.Status = val
}

// SetAuthor sets the value of Author.
func (s *Note) SetAuthor(val string) {
	s.Author = val
}

// SetContent sets the value of Content.
func (s *Note) SetContent(val string) {
	s.Content = val
}

// SetReviews sets the value of Reviews.
func (s *Note) SetReviews(val []Review) {
	s.Reviews = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *Note) SetCreatedAt(val OptDateTime) {
	s.CreatedAt = val
}

// SetUpdatedAt sets the value of UpdatedAt.
func (s *Note) SetUpdatedAt(val OptDateTime) {
	s.UpdatedAt = val
}

// Outgoing(発信)ノートの状態管理用
// - draft: 下書き
// - waiting_review: 添削待ち
// - waiting_sent: 承認完了・送信待ち (Weight >= 5)
// - sent: 送信済み (手動完了)
// - canceled: 破棄.
// Ref: #/components/schemas/NoteStatus
type NoteStatus string

const (
	NoteStatusDraft         NoteStatus = "draft"
	NoteStatusWaitingReview NoteStatus = "waiting_review"
	NoteStatusWaitingSent   NoteStatus = "waiting_sent"
	NoteStatusSent          NoteStatus = "sent"
	NoteStatusCanceled      NoteStatus = "canceled"
)

// AllValues returns all NoteStatus values.
func (NoteStatus) AllValues() []NoteStatus {
	return []NoteStatus{
		NoteStatusDraft,
		NoteStatusWaitingReview,
		NoteStatusWaitingSent,
		NoteStatusSent,
		NoteStatusCanceled,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s NoteStatus) MarshalText() ([]byte, error) {
	switch s {
	case NoteStatusDraft:
		return []byte(s), nil
	case NoteStatusWaitingReview:
		return []byte(s), nil
	case NoteStatusWaitingSent:
		return []byte(s), nil
	case NoteStatusSent:
		return []byte(s), nil
	case NoteStatusCanceled:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *NoteStatus) UnmarshalText(data []byte) error {
	switch NoteStatus(data) {
	case NoteStatusDraft:
		*s = NoteStatusDraft
		return nil
	case NoteStatusWaitingReview:
		*s = NoteStatusWaitingReview
		return nil
	case NoteStatusWaitingSent:
		*s = NoteStatusWaitingSent
		return nil
	case NoteStatusSent:
		*s = NoteStatusSent
		return nil
	case NoteStatusCanceled:
		*s = NoteStatusCanceled
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// ノートの種類 (発信/受信/その他).
// Ref: #/components/schemas/NoteType
type NoteType string

const (
	NoteTypeOutgoing NoteType = "outgoing"
	NoteTypeIncoming NoteType = "incoming"
	NoteTypeOther    NoteType = "other"
)

// AllValues returns all NoteType values.
func (NoteType) AllValues() []NoteType {
	return []NoteType{
		NoteTypeOutgoing,
		NoteTypeIncoming,
		NoteTypeOther,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s NoteType) MarshalText() ([]byte, error) {
	switch s {
	case NoteTypeOutgoing:
		return []byte(s), nil
	case NoteTypeIncoming:
		return []byte(s), nil
	case NoteTypeOther:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *NoteType) UnmarshalText(data []byte) error {
	switch NoteType(data) {
	case NoteTypeOutgoing:
		*s = NoteTypeOutgoing
		return nil
	case NoteTypeIncoming:
		*s = NoteTypeIncoming
		return nil
	case NoteTypeOther:
		*s = NoteTypeOther
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// NewOptBool returns new OptBool with value set to v.
func NewOptBool(v bool) OptBool {
	return OptBool{
		Value: v,
		Set:   true,
	}
}

// OptBool is optional bool.
type OptBool struct {
	Value bool
	Set   bool
}

// IsSet returns true if OptBool was set.
func (o OptBool) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptBool) Reset() {
	var v bool
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptBool) SetTo(v bool) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptBool) Get() (v bool, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptBool) Or(d bool) bool {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptDate returns new OptDate with value set to v.
func NewOptDate(v time.Time) OptDate {
	return OptDate{
		Value: v,
		Set:   true,
	}
}

// OptDate is optional time.Time.
type OptDate struct {
	Value time.Time
	Set   bool
}

// IsSet returns true if OptDate was set.
func (o OptDate) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptDate) Reset() {
	var v time.Time
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptDate) SetTo(v time.Time) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptDate) Get() (v time.Time, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptDate) Or(d time.Time) time.Time {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptDateTime returns new OptDateTime with value set to v.
func NewOptDateTime(v time.Time) OptDateTime {
	return OptDateTime{
		Value: v,
		Set:   true,
	}
}

// OptDateTime is optional time.Time.
type OptDateTime struct {
	Value time.Time
	Set   bool
}

// IsSet returns true if OptDateTime was set.
func (o OptDateTime) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptDateTime) Reset() {
	var v time.Time
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptDateTime) SetTo(v time.Time) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptDateTime) Get() (v time.Time, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptDateTime) Or(d time.Time) time.Time {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilDate returns new OptNilDate with value set to v.
func NewOptNilDate(v time.Time) OptNilDate {
	return OptNilDate{
		Value: v,
		Set:   true,
	}
}

// OptNilDate is optional nullable time.Time.
type OptNilDate struct {
	Value time.Time
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilDate was set.
func (o OptNilDate) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilDate) Reset() {
	var v time.Time
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilDate) SetTo(v time.Time) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilDate) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilDate) SetToNull() {
	o.Set = true
	o.Null = true
	var v time.Time
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilDate) Get() (v time.Time, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilDate) Or(d time.Time) time.Time {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNoteStatus returns new OptNoteStatus with value set to v.
func NewOptNoteStatus(v NoteStatus) OptNoteStatus {
	return OptNoteStatus{
		Value: v,
		Set:   true,
	}
}

// OptNoteStatus is optional NoteStatus.
type OptNoteStatus struct {
	Value NoteStatus
	Set   bool
}

// IsSet returns true if OptNoteStatus was set.
func (o OptNoteStatus) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNoteStatus) Reset() {
	var v NoteStatus
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptNoteStatus) SetTo(v NoteStatus) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNoteStatus) Get() (v NoteStatus, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNoteStatus) Or(d NoteStatus) NoteStatus {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptReviewType returns new OptReviewType with value set to v.
func NewOptReviewType(v ReviewType) OptReviewType {
	return OptReviewType{
		Value: v,
		Set:   true,
	}
}

// OptReviewType is optional ReviewType.
type OptReviewType struct {
	Value ReviewType
	Set   bool
}

// IsSet returns true if OptReviewType was set.
func (o OptReviewType) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptReviewType) Reset() {
	var v ReviewType
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptReviewType) SetTo(v ReviewType) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptReviewType) Get() (v ReviewType, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptReviewType) Or(d ReviewType) ReviewType {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptTicketStatus returns new OptTicketStatus with value set to v.
func NewOptTicketStatus(v TicketStatus) OptTicketStatus {
	return OptTicketStatus{
		Value: v,
		Set:   true,
	}
}

// OptTicketStatus is optional TicketStatus.
type OptTicketStatus struct {
	Value TicketStatus
	Set   bool
}

// IsSet returns true if OptTicketStatus was set.
func (o OptTicketStatus) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptTicketStatus) Reset() {
	var v TicketStatus
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptTicketStatus) SetTo(v TicketStatus) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptTicketStatus) Get() (v TicketStatus, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptTicketStatus) Or(d TicketStatus) TicketStatus {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptTicketsGetSort returns new OptTicketsGetSort with value set to v.
func NewOptTicketsGetSort(v TicketsGetSort) OptTicketsGetSort {
	return OptTicketsGetSort{
		Value: v,
		Set:   true,
	}
}

// OptTicketsGetSort is optional TicketsGetSort.
type OptTicketsGetSort struct {
	Value TicketsGetSort
	Set   bool
}

// IsSet returns true if OptTicketsGetSort was set.
func (o OptTicketsGetSort) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptTicketsGetSort) Reset() {
	var v TicketsGetSort
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptTicketsGetSort) SetTo(v TicketsGetSort) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptTicketsGetSort) Get() (v TicketsGetSort, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptTicketsGetSort) Or(d TicketsGetSort) TicketsGetSort {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptTicketsTicketIdPatchReq returns new OptTicketsTicketIdPatchReq with value set to v.
func NewOptTicketsTicketIdPatchReq(v TicketsTicketIdPatchReq) OptTicketsTicketIdPatchReq {
	return OptTicketsTicketIdPatchReq{
		Value: v,
		Set:   true,
	}
}

// OptTicketsTicketIdPatchReq is optional TicketsTicketIdPatchReq.
type OptTicketsTicketIdPatchReq struct {
	Value TicketsTicketIdPatchReq
	Set   bool
}

// IsSet returns true if OptTicketsTicketIdPatchReq was set.
func (o OptTicketsTicketIdPatchReq) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptTicketsTicketIdPatchReq) Reset() {
	var v TicketsTicketIdPatchReq
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptTicketsTicketIdPatchReq) SetTo(v TicketsTicketIdPatchReq) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptTicketsTicketIdPatchReq) Get() (v TicketsTicketIdPatchReq, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptTicketsTicketIdPatchReq) Or(d TicketsTicketIdPatchReq) TicketsTicketIdPatchReq {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptUpdateReviewReq returns new OptUpdateReviewReq with value set to v.
func NewOptUpdateReviewReq(v UpdateReviewReq) OptUpdateReviewReq {
	return OptUpdateReviewReq{
		Value: v,
		Set:   true,
	}
}

// OptUpdateReviewReq is optional UpdateReviewReq.
type OptUpdateReviewReq struct {
	Value UpdateReviewReq
	Set   bool
}

// IsSet returns true if OptUpdateReviewReq was set.
func (o OptUpdateReviewReq) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptUpdateReviewReq) Reset() {
	var v UpdateReviewReq
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptUpdateReviewReq) SetTo(v UpdateReviewReq) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptUpdateReviewReq) Get() (v UpdateReviewReq, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptUpdateReviewReq) Or(d UpdateReviewReq) UpdateReviewReq {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/Review
type Review struct {
	ID     int64 `json:"id"`
	NoteID int64 `json:"note_id"`
	// レビュワー.
	Reviewer string     `json:"reviewer"`
	Type     ReviewType `json:"type"`
	// 承認ウェイト。
	// - 本職: 1-5
	// - 補佐: 1-4
	// - その他: 0.
	Weight int `json:"weight"`
	// レビュー状態 (active: 有効, stale: 修正により無効化済み).
	Status ReviewStatus `json:"status"`
	// コメント.
	Comment   OptString   `json:"comment"`
	CreatedAt OptDateTime `json:"created_at"`
	UpdatedAt OptDateTime `json:"updated_at"`
}

// GetID returns the value of ID.
func (s *Review) GetID() int64 {
	return s.ID
}

// GetNoteID returns the value of NoteID.
func (s *Review) GetNoteID() int64 {
	return s.NoteID
}

// GetReviewer returns the value of Reviewer.
func (s *Review) GetReviewer() string {
	return s.Reviewer
}

// GetType returns the value of Type.
func (s *Review) GetType() ReviewType {
	return s.Type
}

// GetWeight returns the value of Weight.
func (s *Review) GetWeight() int {
	return s.Weight
}

// GetStatus returns the value of Status.
func (s *Review) GetStatus() ReviewStatus {
	return s.Status
}

// GetComment returns the value of Comment.
func (s *Review) GetComment() OptString {
	return s.Comment
}

// GetCreatedAt returns the value of CreatedAt.
func (s *Review) GetCreatedAt() OptDateTime {
	return s.CreatedAt
}

// GetUpdatedAt returns the value of UpdatedAt.
func (s *Review) GetUpdatedAt() OptDateTime {
	return s.UpdatedAt
}

// SetID sets the value of ID.
func (s *Review) SetID(val int64) {
	s.ID = val
}

// SetNoteID sets the value of NoteID.
func (s *Review) SetNoteID(val int64) {
	s.NoteID = val
}

// SetReviewer sets the value of Reviewer.
func (s *Review) SetReviewer(val string) {
	s.Reviewer = val
}

// SetType sets the value of Type.
func (s *Review) SetType(val ReviewType) {
	s.Type = val
}

// SetWeight sets the value of Weight.
func (s *Review) SetWeight(val int) {
	s.Weight = val
}

// SetStatus sets the value of Status.
func (s *Review) SetStatus(val ReviewStatus) {
	s.Status = val
}

// SetComment sets the value of Comment.
func (s *Review) SetComment(val OptString) {
	s.Comment = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *Review) SetCreatedAt(val OptDateTime) {
	s.CreatedAt = val
}

// SetUpdatedAt sets the value of UpdatedAt.
func (s *Review) SetUpdatedAt(val OptDateTime) {
	s.UpdatedAt = val
}

// レビュー状態 (active: 有効, stale: 修正により無効化済み).
type ReviewStatus string

const (
	ReviewStatusActive ReviewStatus = "active"
	ReviewStatusStale  ReviewStatus = "stale"
)

// AllValues returns all ReviewStatus values.
func (ReviewStatus) AllValues() []ReviewStatus {
	return []ReviewStatus{
		ReviewStatusActive,
		ReviewStatusStale,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ReviewStatus) MarshalText() ([]byte, error) {
	switch s {
	case ReviewStatusActive:
		return []byte(s), nil
	case ReviewStatusStale:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ReviewStatus) UnmarshalText(data []byte) error {
	switch ReviewStatus(data) {
	case ReviewStatusActive:
		*s = ReviewStatusActive
		return nil
	case ReviewStatusStale:
		*s = ReviewStatusStale
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// レビューの種類.
// Ref: #/components/schemas/ReviewType
type ReviewType string

const (
	ReviewTypeApprove       ReviewType = "approve"
	ReviewTypeChangeRequest ReviewType = "change_request"
	ReviewTypeComment       ReviewType = "comment"
	ReviewTypeSystem        ReviewType = "system"
)

// AllValues returns all ReviewType values.
func (ReviewType) AllValues() []ReviewType {
	return []ReviewType{
		ReviewTypeApprove,
		ReviewTypeChangeRequest,
		ReviewTypeComment,
		ReviewTypeSystem,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ReviewType) MarshalText() ([]byte, error) {
	switch s {
	case ReviewTypeApprove:
		return []byte(s), nil
	case ReviewTypeChangeRequest:
		return []byte(s), nil
	case ReviewTypeComment:
		return []byte(s), nil
	case ReviewTypeSystem:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ReviewType) UnmarshalText(data []byte) error {
	switch ReviewType(data) {
	case ReviewTypeApprove:
		*s = ReviewTypeApprove
		return nil
	case ReviewTypeChangeRequest:
		*s = ReviewTypeChangeRequest
		return nil
	case ReviewTypeComment:
		*s = ReviewTypeComment
		return nil
	case ReviewTypeSystem:
		*s = ReviewTypeSystem
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/Ticket
type Ticket struct {
	// チケットID.
	ID int64 `json:"id"`
	// 案件名.
	Title string `json:"title"`
	// 詳細.
	Description OptString `json:"description"`
	// 主担当のtraQ ID.
	Assignee string `json:"assignee"`
	// 副担当リスト (traQ ID).
	SubAssignees []string `json:"sub_assignees"`
	// その他関係者リスト (traQ ID)。.
	Stakeholders []string     `json:"stakeholders"`
	Status       TicketStatus `json:"status"`
	// タグ (例: 協賛, 問い合わせ).
	Tags []string `json:"tags"`
	// 期日。未指定時は自動設定される。.
	Due       OptNilDate  `json:"due"`
	CreatedAt time.Time   `json:"created_at"`
	UpdatedAt OptDateTime `json:"updated_at"`
}

// GetID returns the value of ID.
func (s *Ticket) GetID() int64 {
	return s.ID
}

// GetTitle returns the value of Title.
func (s *Ticket) GetTitle() string {
	return s.Title
}

// GetDescription returns the value of Description.
func (s *Ticket) GetDescription() OptString {
	return s.Description
}

// GetAssignee returns the value of Assignee.
func (s *Ticket) GetAssignee() string {
	return s.Assignee
}

// GetSubAssignees returns the value of SubAssignees.
func (s *Ticket) GetSubAssignees() []string {
	return s.SubAssignees
}

// GetStakeholders returns the value of Stakeholders.
func (s *Ticket) GetStakeholders() []string {
	return s.Stakeholders
}

// GetStatus returns the value of Status.
func (s *Ticket) GetStatus() TicketStatus {
	return s.Status
}

// GetTags returns the value of Tags.
func (s *Ticket) GetTags() []string {
	return s.Tags
}

// GetDue returns the value of Due.
func (s *Ticket) GetDue() OptNilDate {
	return s.Due
}

// GetCreatedAt returns the value of CreatedAt.
func (s *Ticket) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// GetUpdatedAt returns the value of UpdatedAt.
func (s *Ticket) GetUpdatedAt() OptDateTime {
	return s.UpdatedAt
}

// SetID sets the value of ID.
func (s *Ticket) SetID(val int64) {
	s.ID = val
}

// SetTitle sets the value of Title.
func (s *Ticket) SetTitle(val string) {
	s.Title = val
}

// SetDescription sets the value of Description.
func (s *Ticket) SetDescription(val OptString) {
	s.Description = val
}

// SetAssignee sets the value of Assignee.
func (s *Ticket) SetAssignee(val string) {
	s.Assignee = val
}

// SetSubAssignees sets the value of SubAssignees.
func (s *Ticket) SetSubAssignees(val []string) {
	s.SubAssignees = val
}

// SetStakeholders sets the value of Stakeholders.
func (s *Ticket) SetStakeholders(val []string) {
	s.Stakeholders = val
}

// SetStatus sets the value of Status.
func (s *Ticket) SetStatus(val TicketStatus) {
	s.Status = val
}

// SetTags sets the value of Tags.
func (s *Ticket) SetTags(val []string) {
	s.Tags = val
}

// SetDue sets the value of Due.
func (s *Ticket) SetDue(val OptNilDate) {
	s.Due = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *Ticket) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// SetUpdatedAt sets the value of UpdatedAt.
func (s *Ticket) SetUpdatedAt(val OptDateTime) {
	s.UpdatedAt = val
}

func (*Ticket) ticketsPostRes() {}

// チケットの進行状況
// - not_planned: 方針決定待ち
// - not_written: メールが書かれていない
// - waiting_review: レビューを待っている
// - waiting_sent: レビューが終わっている
// - sent: 相手の対応待ち (送信済み)
// - milestone_scheduled: 次のアクション決定済み
// - completed: 完了
// - forgotten: 忘れ去られた状態.
// Ref: #/components/schemas/TicketStatus
type TicketStatus string

const (
	TicketStatusNotPlanned         TicketStatus = "not_planned"
	TicketStatusNotWritten         TicketStatus = "not_written"
	TicketStatusWaitingReview      TicketStatus = "waiting_review"
	TicketStatusWaitingSent        TicketStatus = "waiting_sent"
	TicketStatusSent               TicketStatus = "sent"
	TicketStatusMilestoneScheduled TicketStatus = "milestone_scheduled"
	TicketStatusCompleted          TicketStatus = "completed"
	TicketStatusForgotten          TicketStatus = "forgotten"
)

// AllValues returns all TicketStatus values.
func (TicketStatus) AllValues() []TicketStatus {
	return []TicketStatus{
		TicketStatusNotPlanned,
		TicketStatusNotWritten,
		TicketStatusWaitingReview,
		TicketStatusWaitingSent,
		TicketStatusSent,
		TicketStatusMilestoneScheduled,
		TicketStatusCompleted,
		TicketStatusForgotten,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s TicketStatus) MarshalText() ([]byte, error) {
	switch s {
	case TicketStatusNotPlanned:
		return []byte(s), nil
	case TicketStatusNotWritten:
		return []byte(s), nil
	case TicketStatusWaitingReview:
		return []byte(s), nil
	case TicketStatusWaitingSent:
		return []byte(s), nil
	case TicketStatusSent:
		return []byte(s), nil
	case TicketStatusMilestoneScheduled:
		return []byte(s), nil
	case TicketStatusCompleted:
		return []byte(s), nil
	case TicketStatusForgotten:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *TicketStatus) UnmarshalText(data []byte) error {
	switch TicketStatus(data) {
	case TicketStatusNotPlanned:
		*s = TicketStatusNotPlanned
		return nil
	case TicketStatusNotWritten:
		*s = TicketStatusNotWritten
		return nil
	case TicketStatusWaitingReview:
		*s = TicketStatusWaitingReview
		return nil
	case TicketStatusWaitingSent:
		*s = TicketStatusWaitingSent
		return nil
	case TicketStatusSent:
		*s = TicketStatusSent
		return nil
	case TicketStatusMilestoneScheduled:
		*s = TicketStatusMilestoneScheduled
		return nil
	case TicketStatusCompleted:
		*s = TicketStatusCompleted
		return nil
	case TicketStatusForgotten:
		*s = TicketStatusForgotten
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// TicketsGetBadRequest is response for TicketsGet operation.
type TicketsGetBadRequest struct{}

func (*TicketsGetBadRequest) ticketsGetRes() {}

type TicketsGetOKApplicationJSON []Ticket

func (*TicketsGetOKApplicationJSON) ticketsGetRes() {}

type TicketsGetSort string

const (
	TicketsGetSortDueAsc      TicketsGetSort = "due_asc"
	TicketsGetSortDueDesc     TicketsGetSort = "due_desc"
	TicketsGetSortCreatedDesc TicketsGetSort = "created_desc"
)

// AllValues returns all TicketsGetSort values.
func (TicketsGetSort) AllValues() []TicketsGetSort {
	return []TicketsGetSort{
		TicketsGetSortDueAsc,
		TicketsGetSortDueDesc,
		TicketsGetSortCreatedDesc,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s TicketsGetSort) MarshalText() ([]byte, error) {
	switch s {
	case TicketsGetSortDueAsc:
		return []byte(s), nil
	case TicketsGetSortDueDesc:
		return []byte(s), nil
	case TicketsGetSortCreatedDesc:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *TicketsGetSort) UnmarshalText(data []byte) error {
	switch TicketsGetSort(data) {
	case TicketsGetSortDueAsc:
		*s = TicketsGetSortDueAsc
		return nil
	case TicketsGetSortDueDesc:
		*s = TicketsGetSortDueDesc
		return nil
	case TicketsGetSortCreatedDesc:
		*s = TicketsGetSortCreatedDesc
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// TicketsGetUnauthorized is response for TicketsGet operation.
type TicketsGetUnauthorized struct{}

func (*TicketsGetUnauthorized) ticketsGetRes() {}

// TicketsPostBadRequest is response for TicketsPost operation.
type TicketsPostBadRequest struct{}

func (*TicketsPostBadRequest) ticketsPostRes() {}

type TicketsPostReq struct {
	Title       string       `json:"title"`
	Description OptString    `json:"description"`
	Status      TicketStatus `json:"status"`
	// 主担当 (traQ ID).
	Assignee string `json:"assignee"`
	// 副担当リスト (traQ ID).
	SubAssignees []string `json:"sub_assignees"`
	// その他関係者 (traQ ID).
	Stakeholders []string `json:"stakeholders"`
	Due          OptDate  `json:"due"`
	Tags         []string `json:"tags"`
}

// GetTitle returns the value of Title.
func (s *TicketsPostReq) GetTitle() string {
	return s.Title
}

// GetDescription returns the value of Description.
func (s *TicketsPostReq) GetDescription() OptString {
	return s.Description
}

// GetStatus returns the value of Status.
func (s *TicketsPostReq) GetStatus() TicketStatus {
	return s.Status
}

// GetAssignee returns the value of Assignee.
func (s *TicketsPostReq) GetAssignee() string {
	return s.Assignee
}

// GetSubAssignees returns the value of SubAssignees.
func (s *TicketsPostReq) GetSubAssignees() []string {
	return s.SubAssignees
}

// GetStakeholders returns the value of Stakeholders.
func (s *TicketsPostReq) GetStakeholders() []string {
	return s.Stakeholders
}

// GetDue returns the value of Due.
func (s *TicketsPostReq) GetDue() OptDate {
	return s.Due
}

// GetTags returns the value of Tags.
func (s *TicketsPostReq) GetTags() []string {
	return s.Tags
}

// SetTitle sets the value of Title.
func (s *TicketsPostReq) SetTitle(val string) {
	s.Title = val
}

// SetDescription sets the value of Description.
func (s *TicketsPostReq) SetDescription(val OptString) {
	s.Description = val
}

// SetStatus sets the value of Status.
func (s *TicketsPostReq) SetStatus(val TicketStatus) {
	s.Status = val
}

// SetAssignee sets the value of Assignee.
func (s *TicketsPostReq) SetAssignee(val string) {
	s.Assignee = val
}

// SetSubAssignees sets the value of SubAssignees.
func (s *TicketsPostReq) SetSubAssignees(val []string) {
	s.SubAssignees = val
}

// SetStakeholders sets the value of Stakeholders.
func (s *TicketsPostReq) SetStakeholders(val []string) {
	s.Stakeholders = val
}

// SetDue sets the value of Due.
func (s *TicketsPostReq) SetDue(val OptDate) {
	s.Due = val
}

// SetTags sets the value of Tags.
func (s *TicketsPostReq) SetTags(val []string) {
	s.Tags = val
}

// TicketsPostUnauthorized is response for TicketsPost operation.
type TicketsPostUnauthorized struct{}

func (*TicketsPostUnauthorized) ticketsPostRes() {}

// TicketsTicketIdDeleteForbidden is response for TicketsTicketIdDelete operation.
type TicketsTicketIdDeleteForbidden struct{}

func (*TicketsTicketIdDeleteForbidden) ticketsTicketIdDeleteRes() {}

// TicketsTicketIdDeleteNoContent is response for TicketsTicketIdDelete operation.
type TicketsTicketIdDeleteNoContent struct{}

func (*TicketsTicketIdDeleteNoContent) ticketsTicketIdDeleteRes() {}

// TicketsTicketIdDeleteNotFound is response for TicketsTicketIdDelete operation.
type TicketsTicketIdDeleteNotFound struct{}

func (*TicketsTicketIdDeleteNotFound) ticketsTicketIdDeleteRes() {}

// TicketsTicketIdGetNotFound is response for TicketsTicketIdGet operation.
type TicketsTicketIdGetNotFound struct{}

func (*TicketsTicketIdGetNotFound) ticketsTicketIdGetRes() {}

// Merged schema.
type TicketsTicketIdGetOK struct {
	// チケットID.
	ID int64 `json:"id"`
	// 案件名.
	Title string `json:"title"`
	// 詳細.
	Description OptString `json:"description"`
	// 主担当のtraQ ID.
	Assignee string `json:"assignee"`
	// 副担当リスト (traQ ID).
	SubAssignees []string `json:"sub_assignees"`
	// その他関係者リスト (traQ ID)。.
	Stakeholders []string     `json:"stakeholders"`
	Status       TicketStatus `json:"status"`
	// タグ (例: 協賛, 問い合わせ).
	Tags []string `json:"tags"`
	// 期日。未指定時は自動設定される。.
	Due       OptNilDate  `json:"due"`
	CreatedAt time.Time   `json:"created_at"`
	UpdatedAt OptDateTime `json:"updated_at"`
	// このチケットに紐づくノート一覧.
	Notes []Note `json:"notes"`
}

// GetID returns the value of ID.
func (s *TicketsTicketIdGetOK) GetID() int64 {
	return s.ID
}

// GetTitle returns the value of Title.
func (s *TicketsTicketIdGetOK) GetTitle() string {
	return s.Title
}

// GetDescription returns the value of Description.
func (s *TicketsTicketIdGetOK) GetDescription() OptString {
	return s.Description
}

// GetAssignee returns the value of Assignee.
func (s *TicketsTicketIdGetOK) GetAssignee() string {
	return s.Assignee
}

// GetSubAssignees returns the value of SubAssignees.
func (s *TicketsTicketIdGetOK) GetSubAssignees() []string {
	return s.SubAssignees
}

// GetStakeholders returns the value of Stakeholders.
func (s *TicketsTicketIdGetOK) GetStakeholders() []string {
	return s.Stakeholders
}

// GetStatus returns the value of Status.
func (s *TicketsTicketIdGetOK) GetStatus() TicketStatus {
	return s.Status
}

// GetTags returns the value of Tags.
func (s *TicketsTicketIdGetOK) GetTags() []string {
	return s.Tags
}

// GetDue returns the value of Due.
func (s *TicketsTicketIdGetOK) GetDue() OptNilDate {
	return s.Due
}

// GetCreatedAt returns the value of CreatedAt.
func (s *TicketsTicketIdGetOK) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// GetUpdatedAt returns the value of UpdatedAt.
func (s *TicketsTicketIdGetOK) GetUpdatedAt() OptDateTime {
	return s.UpdatedAt
}

// GetNotes returns the value of Notes.
func (s *TicketsTicketIdGetOK) GetNotes() []Note {
	return s.Notes
}

// SetID sets the value of ID.
func (s *TicketsTicketIdGetOK) SetID(val int64) {
	s.ID = val
}

// SetTitle sets the value of Title.
func (s *TicketsTicketIdGetOK) SetTitle(val string) {
	s.Title = val
}

// SetDescription sets the value of Description.
func (s *TicketsTicketIdGetOK) SetDescription(val OptString) {
	s.Description = val
}

// SetAssignee sets the value of Assignee.
func (s *TicketsTicketIdGetOK) SetAssignee(val string) {
	s.Assignee = val
}

// SetSubAssignees sets the value of SubAssignees.
func (s *TicketsTicketIdGetOK) SetSubAssignees(val []string) {
	s.SubAssignees = val
}

// SetStakeholders sets the value of Stakeholders.
func (s *TicketsTicketIdGetOK) SetStakeholders(val []string) {
	s.Stakeholders = val
}

// SetStatus sets the value of Status.
func (s *TicketsTicketIdGetOK) SetStatus(val TicketStatus) {
	s.Status = val
}

// SetTags sets the value of Tags.
func (s *TicketsTicketIdGetOK) SetTags(val []string) {
	s.Tags = val
}

// SetDue sets the value of Due.
func (s *TicketsTicketIdGetOK) SetDue(val OptNilDate) {
	s.Due = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *TicketsTicketIdGetOK) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// SetUpdatedAt sets the value of UpdatedAt.
func (s *TicketsTicketIdGetOK) SetUpdatedAt(val OptDateTime) {
	s.UpdatedAt = val
}

// SetNotes sets the value of Notes.
func (s *TicketsTicketIdGetOK) SetNotes(val []Note) {
	s.Notes = val
}

func (*TicketsTicketIdGetOK) ticketsTicketIdGetRes() {}

// TicketsTicketIdNotesNoteIdDeleteNoContent is response for TicketsTicketIdNotesNoteIdDelete operation.
type TicketsTicketIdNotesNoteIdDeleteNoContent struct{}

// TicketsTicketIdNotesNoteIdPutForbidden is response for TicketsTicketIdNotesNoteIdPut operation.
type TicketsTicketIdNotesNoteIdPutForbidden struct{}

func (*TicketsTicketIdNotesNoteIdPutForbidden) ticketsTicketIdNotesNoteIdPutRes() {}

// TicketsTicketIdNotesNoteIdPutOK is response for TicketsTicketIdNotesNoteIdPut operation.
type TicketsTicketIdNotesNoteIdPutOK struct{}

func (*TicketsTicketIdNotesNoteIdPutOK) ticketsTicketIdNotesNoteIdPutRes() {}

type TicketsTicketIdNotesNoteIdPutReq struct {
	Content OptString     `json:"content"`
	Status  OptNoteStatus `json:"status"`
	// Trueの場合、承認状況(Weight)をリセットしてDraftに戻す.
	ResetReviews OptBool `json:"reset_reviews"`
}

// GetContent returns the value of Content.
func (s *TicketsTicketIdNotesNoteIdPutReq) GetContent() OptString {
	return s.Content
}

// GetStatus returns the value of Status.
func (s *TicketsTicketIdNotesNoteIdPutReq) GetStatus() OptNoteStatus {
	return s.Status
}

// GetResetReviews returns the value of ResetReviews.
func (s *TicketsTicketIdNotesNoteIdPutReq) GetResetReviews() OptBool {
	return s.ResetReviews
}

// SetContent sets the value of Content.
func (s *TicketsTicketIdNotesNoteIdPutReq) SetContent(val OptString) {
	s.Content = val
}

// SetStatus sets the value of Status.
func (s *TicketsTicketIdNotesNoteIdPutReq) SetStatus(val OptNoteStatus) {
	s.Status = val
}

// SetResetReviews sets the value of ResetReviews.
func (s *TicketsTicketIdNotesNoteIdPutReq) SetResetReviews(val OptBool) {
	s.ResetReviews = val
}

type TicketsTicketIdNotesPostReq struct {
	Type    NoteType `json:"type"`
	Content string   `json:"content"`
	// 作成時にメンション通知を送るか否か.
	MentionNotification bool `json:"mention_notification"`
}

// GetType returns the value of Type.
func (s *TicketsTicketIdNotesPostReq) GetType() NoteType {
	return s.Type
}

// GetContent returns the value of Content.
func (s *TicketsTicketIdNotesPostReq) GetContent() string {
	return s.Content
}

// GetMentionNotification returns the value of MentionNotification.
func (s *TicketsTicketIdNotesPostReq) GetMentionNotification() bool {
	return s.MentionNotification
}

// SetType sets the value of Type.
func (s *TicketsTicketIdNotesPostReq) SetType(val NoteType) {
	s.Type = val
}

// SetContent sets the value of Content.
func (s *TicketsTicketIdNotesPostReq) SetContent(val string) {
	s.Content = val
}

// SetMentionNotification sets the value of MentionNotification.
func (s *TicketsTicketIdNotesPostReq) SetMentionNotification(val bool) {
	s.MentionNotification = val
}

// TicketsTicketIdPatchBadRequest is response for TicketsTicketIdPatch operation.
type TicketsTicketIdPatchBadRequest struct{}

func (*TicketsTicketIdPatchBadRequest) ticketsTicketIdPatchRes() {}

// TicketsTicketIdPatchForbidden is response for TicketsTicketIdPatch operation.
type TicketsTicketIdPatchForbidden struct{}

func (*TicketsTicketIdPatchForbidden) ticketsTicketIdPatchRes() {}

// TicketsTicketIdPatchNotFound is response for TicketsTicketIdPatch operation.
type TicketsTicketIdPatchNotFound struct{}

func (*TicketsTicketIdPatchNotFound) ticketsTicketIdPatchRes() {}

// TicketsTicketIdPatchOK is response for TicketsTicketIdPatch operation.
type TicketsTicketIdPatchOK struct{}

func (*TicketsTicketIdPatchOK) ticketsTicketIdPatchRes() {}

type TicketsTicketIdPatchReq struct {
	Title        OptString       `json:"title"`
	Description  OptString       `json:"description"`
	Status       OptTicketStatus `json:"status"`
	Assignee     OptString       `json:"assignee"`
	SubAssignees []string        `json:"sub_assignees"`
	Stakeholders []string        `json:"stakeholders"`
	Due          OptDate         `json:"due"`
	Tags         []string        `json:"tags"`
}

// GetTitle returns the value of Title.
func (s *TicketsTicketIdPatchReq) GetTitle() OptString {
	return s.Title
}

// GetDescription returns the value of Description.
func (s *TicketsTicketIdPatchReq) GetDescription() OptString {
	return s.Description
}

// GetStatus returns the value of Status.
func (s *TicketsTicketIdPatchReq) GetStatus() OptTicketStatus {
	return s.Status
}

// GetAssignee returns the value of Assignee.
func (s *TicketsTicketIdPatchReq) GetAssignee() OptString {
	return s.Assignee
}

// GetSubAssignees returns the value of SubAssignees.
func (s *TicketsTicketIdPatchReq) GetSubAssignees() []string {
	return s.SubAssignees
}

// GetStakeholders returns the value of Stakeholders.
func (s *TicketsTicketIdPatchReq) GetStakeholders() []string {
	return s.Stakeholders
}

// GetDue returns the value of Due.
func (s *TicketsTicketIdPatchReq) GetDue() OptDate {
	return s.Due
}

// GetTags returns the value of Tags.
func (s *TicketsTicketIdPatchReq) GetTags() []string {
	return s.Tags
}

// SetTitle sets the value of Title.
func (s *TicketsTicketIdPatchReq) SetTitle(val OptString) {
	s.Title = val
}

// SetDescription sets the value of Description.
func (s *TicketsTicketIdPatchReq) SetDescription(val OptString) {
	s.Description = val
}

// SetStatus sets the value of Status.
func (s *TicketsTicketIdPatchReq) SetStatus(val OptTicketStatus) {
	s.Status = val
}

// SetAssignee sets the value of Assignee.
func (s *TicketsTicketIdPatchReq) SetAssignee(val OptString) {
	s.Assignee = val
}

// SetSubAssignees sets the value of SubAssignees.
func (s *TicketsTicketIdPatchReq) SetSubAssignees(val []string) {
	s.SubAssignees = val
}

// SetStakeholders sets the value of Stakeholders.
func (s *TicketsTicketIdPatchReq) SetStakeholders(val []string) {
	s.Stakeholders = val
}

// SetDue sets the value of Due.
func (s *TicketsTicketIdPatchReq) SetDue(val OptDate) {
	s.Due = val
}

// SetTags sets the value of Tags.
func (s *TicketsTicketIdPatchReq) SetTags(val []string) {
	s.Tags = val
}

type TraQAuth struct {
	APIKey string
	Roles  []string
}

// GetAPIKey returns the value of APIKey.
func (s *TraQAuth) GetAPIKey() string {
	return s.APIKey
}

// GetRoles returns the value of Roles.
func (s *TraQAuth) GetRoles() []string {
	return s.Roles
}

// SetAPIKey sets the value of APIKey.
func (s *TraQAuth) SetAPIKey(val string) {
	s.APIKey = val
}

// SetRoles sets the value of Roles.
func (s *TraQAuth) SetRoles(val []string) {
	s.Roles = val
}

// UpdateReviewForbidden is response for UpdateReview operation.
type UpdateReviewForbidden struct{}

func (*UpdateReviewForbidden) updateReviewRes() {}

// UpdateReviewNotFound is response for UpdateReview operation.
type UpdateReviewNotFound struct{}

func (*UpdateReviewNotFound) updateReviewRes() {}

// UpdateReviewOK is response for UpdateReview operation.
type UpdateReviewOK struct{}

func (*UpdateReviewOK) updateReviewRes() {}

type UpdateReviewReq struct {
	Type    OptReviewType `json:"type"`
	Weight  OptInt        `json:"weight"`
	Comment OptString     `json:"comment"`
}

// GetType returns the value of Type.
func (s *UpdateReviewReq) GetType() OptReviewType {
	return s.Type
}

// GetWeight returns the value of Weight.
func (s *UpdateReviewReq) GetWeight() OptInt {
	return s.Weight
}

// GetComment returns the value of Comment.
func (s *UpdateReviewReq) GetComment() OptString {
	return s.Comment
}

// SetType sets the value of Type.
func (s *UpdateReviewReq) SetType(val OptReviewType) {
	s.Type = val
}

// SetWeight sets the value of Weight.
func (s *UpdateReviewReq) SetWeight(val OptInt) {
	s.Weight = val
}

// SetComment sets the value of Comment.
func (s *UpdateReviewReq) SetComment(val OptString) {
	s.Comment = val
}

// Ref: #/components/schemas/User
type User struct {
	// TraQ ID (例: ramdos).
	TraqID string `json:"traq_id"`
	// ユーザーの役割 (manager: 本職, assistant: 補佐, member: その他).
	Role UserRole `json:"role"`
}

// GetTraqID returns the value of TraqID.
func (s *User) GetTraqID() string {
	return s.TraqID
}

// GetRole returns the value of Role.
func (s *User) GetRole() UserRole {
	return s.Role
}

// SetTraqID sets the value of TraqID.
func (s *User) SetTraqID(val string) {
	s.TraqID = val
}

// SetRole sets the value of Role.
func (s *User) SetRole(val UserRole) {
	s.Role = val
}

// ユーザーの役割 (manager: 本職, assistant: 補佐, member: その他).
type UserRole string

const (
	UserRoleManager   UserRole = "manager"
	UserRoleAssistant UserRole = "assistant"
	UserRoleMember    UserRole = "member"
)

// AllValues returns all UserRole values.
func (UserRole) AllValues() []UserRole {
	return []UserRole{
		UserRoleManager,
		UserRoleAssistant,
		UserRoleMember,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s UserRole) MarshalText() ([]byte, error) {
	switch s {
	case UserRoleManager:
		return []byte(s), nil
	case UserRoleAssistant:
		return []byte(s), nil
	case UserRoleMember:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *UserRole) UnmarshalText(data []byte) error {
	switch UserRole(data) {
	case UserRoleManager:
		*s = UserRoleManager
		return nil
	case UserRoleAssistant:
		*s = UserRoleAssistant
		return nil
	case UserRoleMember:
		*s = UserRoleMember
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// UsersPutForbidden is response for UsersPut operation.
type UsersPutForbidden struct{}

func (*UsersPutForbidden) usersPutRes() {}

// UsersPutOK is response for UsersPut operation.
type UsersPutOK struct{}

func (*UsersPutOK) usersPutRes() {}
