// Code generated by ogen, DO NOT EDIT.
package api

type ConfigGetRes interface {
	configGetRes()
}

type ConfigPostRes interface {
	configPostRes()
}

type CreateTicketRes interface {
	createTicketRes()
}

type DeleteTicketByIDRes interface {
	deleteTicketByIDRes()
}

type GetTicketByIDRes interface {
	getTicketByIDRes()
}

type GetTicketsRes interface {
	getTicketsRes()
}

type TicketsTicketIdNotesNoteIdPutRes interface {
	ticketsTicketIdNotesNoteIdPutRes()
}

type UpdateReviewRes interface {
	updateReviewRes()
}

type UpdateTicketByIDRes interface {
	updateTicketByIDRes()
}

type UsersPutRes interface {
	usersPutRes()
}
