// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	ConfigGetOperation                        OperationName = "ConfigGet"
	ConfigPostOperation                       OperationName = "ConfigPost"
	CreateReviewOperation                     OperationName = "CreateReview"
	DeleteReviewOperation                     OperationName = "DeleteReview"
	TicketsGetOperation                       OperationName = "TicketsGet"
	TicketsPostOperation                      OperationName = "TicketsPost"
	TicketsTicketIdAiGeneratePostOperation    OperationName = "TicketsTicketIdAiGeneratePost"
	TicketsTicketIdDeleteOperation            OperationName = "TicketsTicketIdDelete"
	TicketsTicketIdGetOperation               OperationName = "TicketsTicketIdGet"
	TicketsTicketIdNotesNoteIdDeleteOperation OperationName = "TicketsTicketIdNotesNoteIdDelete"
	TicketsTicketIdNotesNoteIdPutOperation    OperationName = "TicketsTicketIdNotesNoteIdPut"
	TicketsTicketIdNotesPostOperation         OperationName = "TicketsTicketIdNotesPost"
	TicketsTicketIdPatchOperation             OperationName = "TicketsTicketIdPatch"
	UpdateReviewOperation                     OperationName = "UpdateReview"
	UsersGetOperation                         OperationName = "UsersGet"
	UsersPutOperation                         OperationName = "UsersPut"
)
