// Code generated by ogen, DO NOT EDIT.

package api

import (
	"net/http"
	"net/url"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// CreateReviewParams is parameters of createReview operation.
type CreateReviewParams struct {
	TicketId int64
	NoteId   int64
}

func unpackCreateReviewParams(packed middleware.Parameters) (params CreateReviewParams) {
	{
		key := middleware.ParameterKey{
			Name: "ticketId",
			In:   "path",
		}
		params.TicketId = packed[key].(int64)
	}
	{
		key := middleware.ParameterKey{
			Name: "noteId",
			In:   "path",
		}
		params.NoteId = packed[key].(int64)
	}
	return params
}

func decodeCreateReviewParams(args [2]string, argsEscaped bool, r *http.Request) (params CreateReviewParams, _ error) {
	// Decode path: ticketId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "ticketId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt64(val)
				if err != nil {
					return err
				}

				params.TicketId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "ticketId",
			In:   "path",
			Err:  err,
		}
	}
	// Decode path: noteId.
	if err := func() error {
		param := args[1]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[1])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "noteId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt64(val)
				if err != nil {
					return err
				}

				params.NoteId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "noteId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// DeleteReviewParams is parameters of deleteReview operation.
type DeleteReviewParams struct {
	TicketId int64
	NoteId   int64
	ReviewId int64
}

func unpackDeleteReviewParams(packed middleware.Parameters) (params DeleteReviewParams) {
	{
		key := middleware.ParameterKey{
			Name: "ticketId",
			In:   "path",
		}
		params.TicketId = packed[key].(int64)
	}
	{
		key := middleware.ParameterKey{
			Name: "noteId",
			In:   "path",
		}
		params.NoteId = packed[key].(int64)
	}
	{
		key := middleware.ParameterKey{
			Name: "reviewId",
			In:   "path",
		}
		params.ReviewId = packed[key].(int64)
	}
	return params
}

func decodeDeleteReviewParams(args [3]string, argsEscaped bool, r *http.Request) (params DeleteReviewParams, _ error) {
	// Decode path: ticketId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "ticketId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt64(val)
				if err != nil {
					return err
				}

				params.TicketId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "ticketId",
			In:   "path",
			Err:  err,
		}
	}
	// Decode path: noteId.
	if err := func() error {
		param := args[1]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[1])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "noteId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt64(val)
				if err != nil {
					return err
				}

				params.NoteId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "noteId",
			In:   "path",
			Err:  err,
		}
	}
	// Decode path: reviewId.
	if err := func() error {
		param := args[2]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[2])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "reviewId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt64(val)
				if err != nil {
					return err
				}

				params.ReviewId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "reviewId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// TicketsGetParams is parameters of GET /tickets operation.
type TicketsGetParams struct {
	// 担当者IDでフィルタ.
	Assignee OptString `json:",omitempty,omitzero"`
	// ステータスでフィルタ.
	Status OptTicketStatus `json:",omitempty,omitzero"`
	// ソート順.
	Sort OptTicketsGetSort `json:",omitempty,omitzero"`
}

func unpackTicketsGetParams(packed middleware.Parameters) (params TicketsGetParams) {
	{
		key := middleware.ParameterKey{
			Name: "assignee",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Assignee = v.(OptString)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "status",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Status = v.(OptTicketStatus)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "sort",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Sort = v.(OptTicketsGetSort)
		}
	}
	return params
}

func decodeTicketsGetParams(args [0]string, argsEscaped bool, r *http.Request) (params TicketsGetParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: assignee.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "assignee",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotAssigneeVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotAssigneeVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Assignee.SetTo(paramsDotAssigneeVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "assignee",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: status.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "status",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotStatusVal TicketStatus
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotStatusVal = TicketStatus(c)
					return nil
				}(); err != nil {
					return err
				}
				params.Status.SetTo(paramsDotStatusVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.Status.Get(); ok {
					if err := func() error {
						if err := value.Validate(); err != nil {
							return err
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "status",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: sort.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "sort",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotSortVal TicketsGetSort
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotSortVal = TicketsGetSort(c)
					return nil
				}(); err != nil {
					return err
				}
				params.Sort.SetTo(paramsDotSortVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.Sort.Get(); ok {
					if err := func() error {
						if err := value.Validate(); err != nil {
							return err
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "sort",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// TicketsTicketIdDeleteParams is parameters of DELETE /tickets/{ticketId} operation.
type TicketsTicketIdDeleteParams struct {
	TicketId int64
}

func unpackTicketsTicketIdDeleteParams(packed middleware.Parameters) (params TicketsTicketIdDeleteParams) {
	{
		key := middleware.ParameterKey{
			Name: "ticketId",
			In:   "path",
		}
		params.TicketId = packed[key].(int64)
	}
	return params
}

func decodeTicketsTicketIdDeleteParams(args [1]string, argsEscaped bool, r *http.Request) (params TicketsTicketIdDeleteParams, _ error) {
	// Decode path: ticketId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "ticketId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt64(val)
				if err != nil {
					return err
				}

				params.TicketId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "ticketId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// TicketsTicketIdGetParams is parameters of GET /tickets/{ticketId} operation.
type TicketsTicketIdGetParams struct {
	TicketId int64
}

func unpackTicketsTicketIdGetParams(packed middleware.Parameters) (params TicketsTicketIdGetParams) {
	{
		key := middleware.ParameterKey{
			Name: "ticketId",
			In:   "path",
		}
		params.TicketId = packed[key].(int64)
	}
	return params
}

func decodeTicketsTicketIdGetParams(args [1]string, argsEscaped bool, r *http.Request) (params TicketsTicketIdGetParams, _ error) {
	// Decode path: ticketId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "ticketId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt64(val)
				if err != nil {
					return err
				}

				params.TicketId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "ticketId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// TicketsTicketIdNotesNoteIdDeleteParams is parameters of DELETE /tickets/{ticketId}/notes/{noteId} operation.
type TicketsTicketIdNotesNoteIdDeleteParams struct {
	TicketId int64
	NoteId   int64
}

func unpackTicketsTicketIdNotesNoteIdDeleteParams(packed middleware.Parameters) (params TicketsTicketIdNotesNoteIdDeleteParams) {
	{
		key := middleware.ParameterKey{
			Name: "ticketId",
			In:   "path",
		}
		params.TicketId = packed[key].(int64)
	}
	{
		key := middleware.ParameterKey{
			Name: "noteId",
			In:   "path",
		}
		params.NoteId = packed[key].(int64)
	}
	return params
}

func decodeTicketsTicketIdNotesNoteIdDeleteParams(args [2]string, argsEscaped bool, r *http.Request) (params TicketsTicketIdNotesNoteIdDeleteParams, _ error) {
	// Decode path: ticketId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "ticketId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt64(val)
				if err != nil {
					return err
				}

				params.TicketId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "ticketId",
			In:   "path",
			Err:  err,
		}
	}
	// Decode path: noteId.
	if err := func() error {
		param := args[1]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[1])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "noteId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt64(val)
				if err != nil {
					return err
				}

				params.NoteId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "noteId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// TicketsTicketIdNotesNoteIdPutParams is parameters of PUT /tickets/{ticketId}/notes/{noteId} operation.
type TicketsTicketIdNotesNoteIdPutParams struct {
	TicketId int64
	NoteId   int64
}

func unpackTicketsTicketIdNotesNoteIdPutParams(packed middleware.Parameters) (params TicketsTicketIdNotesNoteIdPutParams) {
	{
		key := middleware.ParameterKey{
			Name: "ticketId",
			In:   "path",
		}
		params.TicketId = packed[key].(int64)
	}
	{
		key := middleware.ParameterKey{
			Name: "noteId",
			In:   "path",
		}
		params.NoteId = packed[key].(int64)
	}
	return params
}

func decodeTicketsTicketIdNotesNoteIdPutParams(args [2]string, argsEscaped bool, r *http.Request) (params TicketsTicketIdNotesNoteIdPutParams, _ error) {
	// Decode path: ticketId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "ticketId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt64(val)
				if err != nil {
					return err
				}

				params.TicketId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "ticketId",
			In:   "path",
			Err:  err,
		}
	}
	// Decode path: noteId.
	if err := func() error {
		param := args[1]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[1])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "noteId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt64(val)
				if err != nil {
					return err
				}

				params.NoteId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "noteId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// TicketsTicketIdNotesPostParams is parameters of POST /tickets/{ticketId}/notes operation.
type TicketsTicketIdNotesPostParams struct {
	TicketId int64
}

func unpackTicketsTicketIdNotesPostParams(packed middleware.Parameters) (params TicketsTicketIdNotesPostParams) {
	{
		key := middleware.ParameterKey{
			Name: "ticketId",
			In:   "path",
		}
		params.TicketId = packed[key].(int64)
	}
	return params
}

func decodeTicketsTicketIdNotesPostParams(args [1]string, argsEscaped bool, r *http.Request) (params TicketsTicketIdNotesPostParams, _ error) {
	// Decode path: ticketId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "ticketId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt64(val)
				if err != nil {
					return err
				}

				params.TicketId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "ticketId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// TicketsTicketIdPatchParams is parameters of PATCH /tickets/{ticketId} operation.
type TicketsTicketIdPatchParams struct {
	TicketId int64
}

func unpackTicketsTicketIdPatchParams(packed middleware.Parameters) (params TicketsTicketIdPatchParams) {
	{
		key := middleware.ParameterKey{
			Name: "ticketId",
			In:   "path",
		}
		params.TicketId = packed[key].(int64)
	}
	return params
}

func decodeTicketsTicketIdPatchParams(args [1]string, argsEscaped bool, r *http.Request) (params TicketsTicketIdPatchParams, _ error) {
	// Decode path: ticketId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "ticketId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt64(val)
				if err != nil {
					return err
				}

				params.TicketId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "ticketId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// UpdateReviewParams is parameters of updateReview operation.
type UpdateReviewParams struct {
	TicketId int64
	NoteId   int64
	ReviewId int64
}

func unpackUpdateReviewParams(packed middleware.Parameters) (params UpdateReviewParams) {
	{
		key := middleware.ParameterKey{
			Name: "ticketId",
			In:   "path",
		}
		params.TicketId = packed[key].(int64)
	}
	{
		key := middleware.ParameterKey{
			Name: "noteId",
			In:   "path",
		}
		params.NoteId = packed[key].(int64)
	}
	{
		key := middleware.ParameterKey{
			Name: "reviewId",
			In:   "path",
		}
		params.ReviewId = packed[key].(int64)
	}
	return params
}

func decodeUpdateReviewParams(args [3]string, argsEscaped bool, r *http.Request) (params UpdateReviewParams, _ error) {
	// Decode path: ticketId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "ticketId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt64(val)
				if err != nil {
					return err
				}

				params.TicketId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "ticketId",
			In:   "path",
			Err:  err,
		}
	}
	// Decode path: noteId.
	if err := func() error {
		param := args[1]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[1])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "noteId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt64(val)
				if err != nil {
					return err
				}

				params.NoteId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "noteId",
			In:   "path",
			Err:  err,
		}
	}
	// Decode path: reviewId.
	if err := func() error {
		param := args[2]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[2])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "reviewId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt64(val)
				if err != nil {
					return err
				}

				params.ReviewId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "reviewId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}
