// Code generated by ogen, DO NOT EDIT.

package api

// setDefaults set default value of fields.
func (s *TicketsTicketIdNotesNoteIdPutReq) setDefaults() {
	{
		val := bool(true)
		s.ResetReviews.SetTo(val)
	}
}
