// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	ConfigGetOperation                                       OperationName = "ConfigGet"
	ConfigPostOperation                                      OperationName = "ConfigPost"
	TicketsGetOperation                                      OperationName = "TicketsGet"
	TicketsPostOperation                                     OperationName = "TicketsPost"
	TicketsTicketIdDeleteOperation                           OperationName = "TicketsTicketIdDelete"
	TicketsTicketIdGetOperation                              OperationName = "TicketsTicketIdGet"
	TicketsTicketIdNotesNoteIdDeleteOperation                OperationName = "TicketsTicketIdNotesNoteIdDelete"
	TicketsTicketIdNotesNoteIdPutOperation                   OperationName = "TicketsTicketIdNotesNoteIdPut"
	TicketsTicketIdNotesNoteIdReviewsPostOperation           OperationName = "TicketsTicketIdNotesNoteIdReviewsPost"
	TicketsTicketIdNotesNoteIdReviewsReviewIdDeleteOperation OperationName = "TicketsTicketIdNotesNoteIdReviewsReviewIdDelete"
	TicketsTicketIdNotesNoteIdReviewsReviewIdPutOperation    OperationName = "TicketsTicketIdNotesNoteIdReviewsReviewIdPut"
	TicketsTicketIdNotesPostOperation                        OperationName = "TicketsTicketIdNotesPost"
	TicketsTicketIdPatchOperation                            OperationName = "TicketsTicketIdPatch"
	UsersGetOperation                                        OperationName = "UsersGet"
	UsersPutOperation                                        OperationName = "UsersPut"
)
