// Code generated by ogen, DO NOT EDIT.
package api

type ConfigGetRes interface {
	configGetRes()
}

type ConfigPostRes interface {
	configPostRes()
}

type CreateReviewRes interface {
	createReviewRes()
}

type CreateTicketRes interface {
	createTicketRes()
}

type DeleteReviewRes interface {
	deleteReviewRes()
}

type DeleteTicketByIDRes interface {
	deleteTicketByIDRes()
}

type GetTicketByIDRes interface {
	getTicketByIDRes()
}

type GetTicketsRes interface {
	getTicketsRes()
}

type MeGetRes interface {
	meGetRes()
}

type TicketsTicketIdAiGeneratePostRes interface {
	ticketsTicketIdAiGeneratePostRes()
}

type TicketsTicketIdNotesNoteIdAiReviewPostRes interface {
	ticketsTicketIdNotesNoteIdAiReviewPostRes()
}

type TicketsTicketIdNotesNoteIdDeleteRes interface {
	ticketsTicketIdNotesNoteIdDeleteRes()
}

type TicketsTicketIdNotesNoteIdPutRes interface {
	ticketsTicketIdNotesNoteIdPutRes()
}

type TicketsTicketIdNotesPostRes interface {
	ticketsTicketIdNotesPostRes()
}

type UpdateReviewRes interface {
	updateReviewRes()
}

type UpdateTicketByIDRes interface {
	updateTicketByIDRes()
}

type UsersGetRes interface {
	usersGetRes()
}

type UsersPutRes interface {
	usersPutRes()
}
