// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
	"net/http"
	"strings"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/ogenerrors"
)

// SecurityHandler is handler for security parameters.
type SecurityHandler interface {
	// HandleTraQAuth handles traQAuth security.
	// TraQ IDをヘッダーに付与して認証.
	HandleTraQAuth(ctx context.Context, operationName OperationName, t TraQAuth) (context.Context, error)
}

func findAuthorization(h http.Header, prefix string) (string, bool) {
	v, ok := h["Authorization"]
	if !ok {
		return "", false
	}
	for _, vv := range v {
		scheme, value, ok := strings.Cut(vv, " ")
		if !ok || !strings.EqualFold(scheme, prefix) {
			continue
		}
		return value, true
	}
	return "", false
}

var operationRolesTraQAuth = map[string][]string{
	ConfigGetOperation:                                       []string{},
	ConfigPostOperation:                                      []string{},
	TicketsGetOperation:                                      []string{},
	TicketsPostOperation:                                     []string{},
	TicketsTicketIdDeleteOperation:                           []string{},
	TicketsTicketIdGetOperation:                              []string{},
	TicketsTicketIdNotesNoteIdDeleteOperation:                []string{},
	TicketsTicketIdNotesNoteIdPutOperation:                   []string{},
	TicketsTicketIdNotesNoteIdReviewsPostOperation:           []string{},
	TicketsTicketIdNotesNoteIdReviewsReviewIdDeleteOperation: []string{},
	TicketsTicketIdNotesNoteIdReviewsReviewIdPutOperation:    []string{},
	TicketsTicketIdNotesPostOperation:                        []string{},
	TicketsTicketIdPatchOperation:                            []string{},
	UsersGetOperation:                                        []string{},
	UsersPutOperation:                                        []string{},
}

func (s *Server) securityTraQAuth(ctx context.Context, operationName OperationName, req *http.Request) (context.Context, bool, error) {
	var t TraQAuth
	const parameterName = "X-Forwarded-User"
	value := req.Header.Get(parameterName)
	if value == "" {
		return ctx, false, nil
	}
	t.APIKey = value
	t.Roles = operationRolesTraQAuth[operationName]
	rctx, err := s.sec.HandleTraQAuth(ctx, operationName, t)
	if errors.Is(err, ogenerrors.ErrSkipServerSecurity) {
		return nil, false, nil
	} else if err != nil {
		return nil, false, err
	}
	return rctx, true, err
}

// SecuritySource is provider of security values (tokens, passwords, etc.).
type SecuritySource interface {
	// TraQAuth provides traQAuth security value.
	// TraQ IDをヘッダーに付与して認証.
	TraQAuth(ctx context.Context, operationName OperationName) (TraQAuth, error)
}

func (s *Client) securityTraQAuth(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.TraQAuth(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"TraQAuth\"")
	}
	req.Header.Set("X-Forwarded-User", t.APIKey)
	return nil
}
